services:
  # Backend service
  - type: web
    name: workify-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn workify.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '*'
      - key: CORS_ALLOW_ALL_ORIGINS
        value: 'True'
      - key: DATABASE_URL
        fromDatabase:
          name: workify-db
          property: connectionString

databases:
  - name: workify-db
    databaseName: workify
    user: workify_user
    plan: free
